pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-southeast-2'
        AWS_ACCOUNT_ID     = '500345929326'
        ECR_REPO           = 'ecommerce-react'
        IMAGE_TAG          = "build-${env.BUILD_NUMBER}"
        ECR_URL            = "${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-2.amazonaws.com"
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${ECR_REPO}:${IMAGE_TAG} ./react-frontend/"
            }
        }

        stage('Trivy Security Scan') {
            steps {
                sh """
                    trivy image \
                      --severity CRITICAL \
                      --exit-code 1 \
                      --no-progress \
                      ${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }

        stage('Push to ECR') {
            steps {
                sh """
                    aws ecr get-login-password \
                      --region ${AWS_DEFAULT_REGION} | \
                    docker login \
                      --username AWS \
                      --password-stdin ${ECR_URL}

                    docker tag ${ECR_REPO}:${IMAGE_TAG} \
                      ${ECR_URL}/${ECR_REPO}:${IMAGE_TAG}

                    docker push \
                      ${ECR_URL}/${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }

    stage('Update Helm Values') {
    steps {
        sh '''
            git checkout -B main origin/main
            sed -i 's|tag:.*|tag: "build-${BUILD_NUMBER}"|g' helm/react-chart/values.yaml
            git config user.email "jenkins@ci.com"
            git config user.name "Jenkins"
            git add helm/react-chart/values.yaml
            git commit -m "ci: update react image to build-${BUILD_NUMBER}"
            git push origin main
        '''
    }
}

    post {
        success {
            echo '✅ React pipeline success! Argo CD will deploy!'
        }
        failure {
            echo '❌ Pipeline failed! Check Trivy scan or build!'
        }
        always {
            sh "docker rmi ${ECR_REPO}:${IMAGE_TAG} || true"
        }
    }
}
